version: '2'
services:
  keepalived:
    image: {{ $.Values.imageRepository }}/public/osixia/keepalived:2.0.20
    container_name: keepalived
    hostname: keepalived
    volumes:
    - ./check_apiserver.sh:/container/service/keepalived/assets/check_apiserver.sh
    - ./keepalived.conf:/container/service/keepalived/assets/keepalived.conf
    cap_add:
    - NET_ADMIN
    command: --copy-service
    network_mode: host
    restart: always
