apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: {{ $.Values.kubernetesVersion }}
{{- if $.Values.imageRepository }}
imageRepository: {{ $.Values.imageRepository }}
{{- end }}
apiServer:
  certSANs:
  - {{ $.Values.kubernetesInfo.kubernetesVname | quote }}
  {{- range $i, $host := $.Values.kubernetesInfo.kubernetesHosts }}
  - {{ $host.hostName | quote }}
  {{- end }}
  - {{ $.Values.kubernetesInfo.kubernetesVip | quote }}
  {{- range $i, $host := $.Values.kubernetesInfo.kubernetesHosts }}
  - {{ $host.hostIP | quote }}
  {{- end }}
controlPlaneEndpoint: "{{ $.Values.kubernetesInfo.kubernetesVip }}:16443"
networking:
  podSubnet: {{ $.Values.calicoSettings.calicoIPv4PoolCIDR | quote }}

