apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  name: nginx-lb
  namespace: kube-system
spec:
  volumes:
  - name: nginx-lb-conf
    hostPath:
      type: File
      path: /etc/kubernetes/manifests/nginx-lb/nginx-lb.conf
  containers:
  - name: nginx-lb
    image: nginx:1.19.7-alpine
    imagePullPolicy: IfNotPresent
    ports:
    - name: apiserver
      containerPort: 16443
      hostPort: 16443
    livenessProbe:
      failureThreshold: 8
      tcpSocket:
        port: 16443
      periodSeconds: 10  
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
    - name: nginx-lb-conf
      mountPath: /etc/nginx/nginx.conf
      readOnly: true
  priorityClassName: system-cluster-critical
